import React, { useCallback, useEffect, useMemo, useState } from "react";
import { api } from "@/lib/api";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";
import { scheduleDriveSync } from "@/lib/drive";
import { useNavigate } from "react-router-dom";
import { CaretDown, CaretUp, CaretUpDown, MagnifyingGlass, PencilSimple, Trash } from "@phosphor-icons/react";
import { TABLE } from "@/constants/testIds";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";

const displayDate=(v)=>{if(!v||v==="—")return v||"—";const p=String(v).slice(0,10).split("-");return p.length===3?`${p[2]}-${p[1]}-${p[0]}`:v;};
const day=(v)=>{if(!v)return null;const x=new Date(`${String(v).slice(0,10)}T00:00:00`).getTime();return Number.isNaN(x)?null:x;};
const tat=(a,b)=>{const x=day(a),y=day(b);return x===null||y===null?null:Math.round((y-x)/86400000);};
const resultText=(t)=>[t?.result1||t?.result_1,t?.result2||t?.result_2].filter(Boolean).join(" / ")||"Pending";
const rowsFor=(r)=>r.tests?.length?r.tests.map((t,i)=>{const rd=t.result_date||t.resultDate||r.result_date||"";return{key:`${r.id}-${i}`,test:t.test||t.name||"—",result:resultText(t),resultDate:rd,tat:tat(r.date,rd)};}):[{key:`${r.id}-legacy`,test:r.test||"—",result:r.results?.length?r.results.map(x=>[x.name,x.value].filter(Boolean).join(" ")).join(", "):"Pending",resultDate:r.result_date||"",tat:tat(r.date,r.result_date)}];
const sortVal=(r,c)=>{const f=rowsFor(r)[0]||{};return({lab_number:r.lab_number||"",date:r.date||"",name:r.name||"",age:Number(r.age??-1),district:r.district||"",sample_type:r.sample_type||"",test:f.test||"",result:f.result||"",result_date:f.resultDate||"",tat:f.tat??Number.MAX_SAFE_INTEGER})[c];};

export default function Records(){
 const nav=useNavigate();const[q,setQ]=useState("");const[page,setPage]=useState(1);const[pageSize,setPageSize]=useState(10);const[sort,setSort]=useState({column:"date",direction:"desc"});const[data,setData]=useState({items:[],total:0,page_size:10});const[loading,setLoading]=useState(false);
 const load=useCallback(async()=>{setLoading(true);try{const r=await api.get("/records",{params:{search:q||undefined,page,page_size:pageSize}});setData(r.data);}catch{toast.error("Failed to load records");}finally{setLoading(false);}},[q,page,pageSize]);
 useEffect(()=>{load();},[load]);
 const items=useMemo(()=>{const d=sort.direction==="asc"?1:-1;return[...(data.items||[])].sort((a,b)=>{const x=sortVal(a,sort.column),y=sortVal(b,sort.column);return(typeof x==="number"&&typeof y==="number"?(x-y):String(x).localeCompare(String(y),undefined,{numeric:true,sensitivity:"base"}))*d;});},[data.items,sort]);
 const toggle=(c)=>setSort(s=>({column:c,direction:s.column===c&&s.direction==="asc"?"desc":"asc"}));
 const del=async(id)=>{try{await api.delete(`/records/${id}`);toast.success("Record deleted");scheduleDriveSync();load();}catch{toast.error("Delete failed");}};
 const pages=Math.max(1,Math.ceil(data.total/pageSize));
 const heads=[["lab_number","Lab #"],["date","Date"],["name","Name"],["age","Age"],["district","District"],["sample_type","Sample"],["test","Test"],["result","Result"],["result_date","Result Date"],["tat","TAT"]];
 return <div className="space-y-4" data-testid="records-page">
  <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-[0.14em] text-slate-500">Line list</div><h1 className="font-heading text-3xl font-semibold text-slate-900 mt-1">All Records</h1></div><div className="flex flex-wrap items-center gap-2"><label className="flex items-center gap-2 text-sm text-slate-600">Records per page<select value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}} className="border rounded p-2 bg-white">{[10,50,100].map(x=><option key={x} value={x}>{x}</option>)}</select></label><div className="relative"><MagnifyingGlass size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><Input placeholder="Search name or lab number" className="pl-9 w-72 bg-white" value={q} onChange={e=>{setPage(1);setQ(e.target.value);}}/></div><Button onClick={()=>nav("/entry")} className="bg-blue-600 hover:bg-blue-700">New Record</Button></div></div>
  <Card className="border border-slate-200 shadow-none bg-white overflow-hidden"><div className="overflow-x-auto"><table data-testid={TABLE.root} className="w-full text-sm zebra"><thead className="bg-white border-b sticky top-0"><tr className="text-left text-[11px] font-semibold uppercase tracking-wider text-slate-500">{heads.map(([c,l])=><th key={c} className="px-3 py-2"><button type="button" onClick={()=>toggle(c)} className="inline-flex items-center gap-1 hover:text-blue-600">{l}{sort.column!==c?<CaretUpDown size={12}/>:sort.direction==="asc"?<CaretUp size={12}/>:<CaretDown size={12}/>}</button></th>)}<th className="px-3 py-2 text-right">Actions</th></tr></thead><tbody className="text-slate-700">
   {loading&&<tr><td colSpan={11} className="p-6 text-center">Loading…</td></tr>}{!loading&&items.length===0&&<tr><td colSpan={11} className="p-10 text-center text-slate-500">No records found.</td></tr>}
   {!loading&&items.flatMap(r=>rowsFor(r).map((x,i)=>{const first=i===0;return <tr key={x.key} className="border-b hover:bg-blue-50/40"><td className="px-3 py-2 font-mono text-xs">{first?r.lab_number:""}</td><td className="px-3 py-2">{first?displayDate(r.date):""}</td><td className="px-3 py-2 font-medium">{first?r.name:""}</td><td className="px-3 py-2">{first?(r.age??"—"):""}</td><td className="px-3 py-2">{first?r.district:""}</td><td className="px-3 py-2">{first?r.sample_type:""}</td><td className="px-3 py-2">{x.test}</td><td className="px-3 py-2"><span className={x.result==="Pending"?"text-amber-600 font-medium":""}>{x.result}</span></td><td className="px-3 py-2">{displayDate(x.resultDate)}</td><td className="px-3 py-2">{x.tat===null?"—":`${x.tat} day${x.tat===1?"":"s"}`}</td><td className="px-3 py-2 text-right">{first&&<div className="inline-flex"><Button variant="ghost" size="icon" onClick={()=>nav(`/entry/${r.id}`)}><PencilSimple size={16}/></Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" className="hover:text-red-600"><Trash size={16}/></Button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this record?</AlertDialogTitle><AlertDialogDescription>Lab #{r.lab_number} · {r.name}. This action cannot be undone.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Cancel</AlertDialogCancel><AlertDialogAction onClick={()=>del(r.id)} className="bg-red-600">Delete</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>}</td></tr>}))}
  </tbody></table></div><div className="px-4 py-3 flex items-center justify-between border-t"><div className="text-xs text-slate-500">Showing {data.items.length} of {data.total} records · Page {page} / {pages}</div><div className="flex gap-2"><Button variant="outline" size="sm" onClick={()=>setPage(p=>Math.max(1,p-1))} disabled={page===1}>Prev</Button><Button variant="outline" size="sm" onClick={()=>setPage(p=>Math.min(pages,p+1))} disabled={page>=pages}>Next</Button></div></div></Card>
 </div>;
}
